# Generated by Django 4.2.7 on 2023-11-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_movement_usercurrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='repeat_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='set_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
