# Generated by Django 4.2.7 on 2023-11-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_movement_goal_movement_video_url_exerciseplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseplan',
            name='goal',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseplan',
            name='plan_duration',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
