# Generated by Django 4.2.7 on 2023-11-30 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_exerciseplanmovement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseplan',
            name='movements',
        ),
        migrations.DeleteModel(
            name='ExercisePlanMovement',
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='movements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.movement'),
        ),
    ]
