# Generated by Django 4.2.7 on 2023-11-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_exerciseplan_movements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseplan',
            name='movements',
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='movements',
            field=models.ManyToManyField(to='users.movement'),
        ),
    ]
