# Generated by Django 4.2.7 on 2023-11-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_exerciseplan_movements_exerciseplan_movements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePlanMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_value', models.IntegerField(blank=True, null=True)),
                ('repeat_value', models.IntegerField(blank=True, null=True)),
                ('exercise_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.exerciseplan')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.movement')),
            ],
        ),
    ]
