# Generated by Django 4.2.7 on 2023-11-30 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_exerciseplanmovement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseplan',
            name='movements',
        ),
        migrations.RemoveField(
            model_name='exerciseplanmovement',
            name='repeat_value',
        ),
        migrations.RemoveField(
            model_name='exerciseplanmovement',
            name='set_value',
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='movement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.movement'),
        ),
    ]
