# Generated by Django 4.2.7 on 2023-11-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_exerciseplan_movements_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseplan',
            old_name='movement',
            new_name='movements',
        ),
    ]
