# Generated by Django 4.2.7 on 2023-11-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_movement_exerciseplan_movements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseplan',
            name='movements',
        ),
        migrations.DeleteModel(
            name='ExercisePlanMovement',
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='movements',
            field=models.ManyToManyField(to='users.movement'),
        ),
    ]
