# Generated by Django 4.2.7 on 2023-11-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_exerciseplan_movements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseplan',
            name='movements',
            field=models.ManyToManyField(blank=True, to='users.movement'),
        ),
    ]
