# Generated by Django 4.2.7 on 2023-11-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_exerciseplan_movements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseplan',
            name='movements',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='repeat_value',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='set_value',
        ),
        migrations.CreateModel(
            name='ExerciseMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_value', models.IntegerField(blank=True, null=True)),
                ('repeat_value', models.IntegerField(blank=True, null=True)),
                ('movement_type', models.ManyToManyField(blank=True, to='users.movement')),
            ],
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('exercises', models.ManyToManyField(blank=True, to='users.exercisemovement')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='daily_plans',
            field=models.ManyToManyField(blank=True, to='users.dailyplan'),
        ),
    ]
