# Generated by Django 4.2.7 on 2023-11-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_dailyplan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplan',
            name='user',
        ),
    ]
