# Generated by Django 4.2.7 on 2023-12-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_dailyplanfood_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplanfood',
            name='foods',
        ),
        migrations.AddField(
            model_name='dailyplanfood',
            name='breakfast_foods',
            field=models.ManyToManyField(blank=True, related_name='breakfast_foods', to='users.food'),
        ),
        migrations.AddField(
            model_name='dailyplanfood',
            name='daily_snacks',
            field=models.ManyToManyField(blank=True, related_name='daily_foods', to='users.food'),
        ),
        migrations.AddField(
            model_name='dailyplanfood',
            name='dinner_foods',
            field=models.ManyToManyField(blank=True, related_name='dinner_foods', to='users.food'),
        ),
        migrations.AddField(
            model_name='dailyplanfood',
            name='lunch_foods',
            field=models.ManyToManyField(blank=True, related_name='lunch_foods', to='users.food'),
        ),
    ]
