# Generated by Django 4.2.7 on 2023-12-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_teacherextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherextra',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
