# Generated by Django 4.2.7 on 2023-12-02 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_teacherextra_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacherextra'),
        ),
    ]
