# Generated by Django 4.2.7 on 2023-12-02 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0021_userextra_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
