# Generated by Django 4.2.7 on 2023-12-03 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0024_alter_teacherextra_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherextra',
            name='students',
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_user: 1'}, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
    ]
