# Generated by Django 4.2.7 on 2023-12-03 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_exercisemovement_movement_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplanfood',
            name='breakfast_foods',
        ),
        migrations.RemoveField(
            model_name='dailyplanfood',
            name='daily_snacks',
        ),
        migrations.RemoveField(
            model_name='dailyplanfood',
            name='dinner_foods',
        ),
        migrations.RemoveField(
            model_name='dailyplanfood',
            name='lunch_foods',
        ),
        migrations.AddField(
            model_name='dailyplanfood',
            name='breakfast_foods',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_foods', to='users.food'),
        ),
        migrations.AddField(
            model_name='dailyplanfood',
            name='daily_snacks',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_foods', to='users.food'),
        ),
        migrations.AddField(
            model_name='dailyplanfood',
            name='dinner_foods',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dinner_foods', to='users.food'),
        ),
        migrations.AddField(
            model_name='dailyplanfood',
            name='lunch_foods',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch_foods', to='users.food'),
        ),
    ]
