# Generated by Django 4.2.7 on 2023-12-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_dailyplanfood_breakfast_foods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplanfood',
            name='breakfast_foods',
        ),
        migrations.RemoveField(
            model_name='dailyplanfood',
            name='daily_snacks',
        ),
        migrations.RemoveField(
            model_name='dailyplanfood',
            name='dinner_foods',
        ),
        migrations.RemoveField(
            model_name='dailyplanfood',
            name='lunch_foods',
        ),
        migrations.RemoveField(
            model_name='exercisemovement',
            name='movement_type',
        ),
        migrations.RemoveField(
            model_name='exerciseplan',
            name='daily_plans',
        ),
        migrations.RemoveField(
            model_name='exerciseplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='foodplan',
            name='daily_plans',
        ),
        migrations.RemoveField(
            model_name='foodplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userextra',
            name='trainer',
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='friday',
            field=models.ManyToManyField(blank=True, null=True, related_name='friday', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='monday',
            field=models.ManyToManyField(blank=True, null=True, related_name='monday', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='saturday',
            field=models.ManyToManyField(blank=True, null=True, related_name='saturday', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='sunday',
            field=models.ManyToManyField(blank=True, null=True, related_name='sunday', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='thursday',
            field=models.ManyToManyField(blank=True, null=True, related_name='thursday', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='tuesday',
            field=models.ManyToManyField(blank=True, null=True, related_name='tuesday', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='wednesday',
            field=models.ManyToManyField(blank=True, null=True, related_name='wednesday', to='users.movement'),
        ),
        migrations.AddField(
            model_name='foodplan',
            name='friday',
            field=models.ManyToManyField(blank=True, null=True, related_name='friday', to='users.food'),
        ),
        migrations.AddField(
            model_name='foodplan',
            name='monday',
            field=models.ManyToManyField(blank=True, null=True, related_name='monday', to='users.food'),
        ),
        migrations.AddField(
            model_name='foodplan',
            name='saturday',
            field=models.ManyToManyField(blank=True, null=True, related_name='saturday', to='users.food'),
        ),
        migrations.AddField(
            model_name='foodplan',
            name='sunday',
            field=models.ManyToManyField(blank=True, null=True, related_name='sunday', to='users.food'),
        ),
        migrations.AddField(
            model_name='foodplan',
            name='thursday',
            field=models.ManyToManyField(blank=True, null=True, related_name='thursday', to='users.food'),
        ),
        migrations.AddField(
            model_name='foodplan',
            name='tuesday',
            field=models.ManyToManyField(blank=True, null=True, related_name='tuesday', to='users.food'),
        ),
        migrations.AddField(
            model_name='foodplan',
            name='wednesday',
            field=models.ManyToManyField(blank=True, null=True, related_name='wednesday', to='users.food'),
        ),
        migrations.AddField(
            model_name='movement',
            name='repeat_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movement',
            name='set_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userextra',
            name='exercise_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.exerciseplan'),
        ),
        migrations.DeleteModel(
            name='DailyPlanExercise',
        ),
        migrations.DeleteModel(
            name='DailyPlanFood',
        ),
        migrations.DeleteModel(
            name='ExerciseMovement',
        ),
    ]
