# Generated by Django 4.2.7 on 2023-12-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_exerciseplan_friday_alter_exerciseplan_monday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodplan',
            name='friday',
            field=models.ManyToManyField(blank=True, null=True, related_name='friday_food', to='users.food'),
        ),
    ]
