# Generated by Django 4.2.7 on 2023-12-04 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_remove_usercurrent_user_userextra_current_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='current_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usercurrent'),
        ),
    ]
