# Generated by Django 4.2.7 on 2023-12-04 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_userextra_current_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='calory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.RemoveField(
            model_name='exerciseplan',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='exerciseplan',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='exerciseplan',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='exerciseplan',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='exerciseplan',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='exerciseplan',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='exerciseplan',
            name='wednesday',
        ),
        migrations.AlterField(
            model_name='userextra',
            name='current_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usercurrent'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='friday',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday_exercise', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='monday',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday_exercise', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='saturday',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_exercise', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='sunday',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_exercise', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='thursday',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_exercise', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='tuesday',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_exercise', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='wednesday',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_exercise', to='users.movement'),
        ),
    ]
