# Generated by Django 4.2.7 on 2023-12-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_userextra_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseplan',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='exerciseplan',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='exerciseplan',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='exerciseplan',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='exerciseplan',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='exerciseplan',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='exerciseplan',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='friday',
            field=models.ManyToManyField(blank=True, related_name='friday_exercise', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='monday',
            field=models.ManyToManyField(blank=True, related_name='monday_exercise', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='saturday',
            field=models.ManyToManyField(blank=True, related_name='saturday_exercise', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='sunday',
            field=models.ManyToManyField(blank=True, related_name='sunday_exercise', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='thursday',
            field=models.ManyToManyField(blank=True, related_name='thursday_exercise', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='tuesday',
            field=models.ManyToManyField(blank=True, related_name='tuesday_exercise', to='users.movement'),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='wednesday',
            field=models.ManyToManyField(blank=True, related_name='wednesday_exercise', to='users.movement'),
        ),
    ]
