# Generated by Django 4.2.7 on 2023-12-05 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_remove_exerciseplan_friday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='food_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.foodplan'),
        ),
    ]
